---
engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      PSR2 Classes PropertyDeclaration Underscore:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/**/*
- src/CodeAutoCompletion/*
